version: "3.6"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    command: /bin/bash /scripts/docker-entrypoint.sh
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=SomeStrongPwd123
    volumes:
      - ./scripts:/scripts
      - './mssqldata:/var/opt/mssql/data'
    networks:
      - default
  piranah:
    build:
      context: ../../../.
      dockerfile: examples/MvcWeb/compose/Dockerfile    
    container_name: 'piranah_container'
    #image: piranah.core:latest
    ports:
      - 57796:57796
    environment:
      - ConnectionStrings:piranha=server=db;Database=piranha;User id=sa;Password=SomeStrongPwd123;Trusted_Connection=False;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:57796
      - ASPNETCORE_HTTPS_PORT=57796 
    networks:
      - default
    links:
      - db   
